In [0]:
import pandas as pd
from geopy.distance import geodesic 
import random

In [0]:
df = pd.read_csv('SCE_0.csv')
df.head()

Unnamed: 0       LAT        LON  sce  sales
0           0  34.09269 -118.31969    0   3.91
1           1  34.27570 -118.41945    0   1.80
2           2  34.29789 -118.57732    0   2.32
3           3  34.07669 -118.23411    0   1.30
4           4  34.03975 -118.30395    0   2.57

In [0]:
#Data Preparing
df0 = df.sample(7) #randomly pick 7 rows
df0["demand"] = df0['sales']*100 #generate the demand
df0['supply'] = 0 #create supply column
for i in range(len(df0['demand'])): # define supply for each retailer
    df0['supply'].iloc[i] = random.randint(0,df0['demand'].iloc[i])
df0

In [0]:
#randomly pick 7 rows
df0 = df.sample(7)

In [0]:
df0["100sales"] = 100*df0.sales

In [0]:
df0

Unnamed: 0       LAT        LON  sce  sales  100sales
299         299  34.02627 -118.25730    0   1.84     184.0
156         156  34.05986 -118.19938    0   1.65     165.0
261         261  34.27019 -118.52950    0   2.55     255.0
138         138  34.08144 -118.30447    0   2.27     227.0
328         328  33.95019 -118.27914    0   2.66     266.0
167         167  34.10100 -118.25150    0   2.80     280.0
151         151  34.05607 -118.35759    0   2.34     234.0

In [0]:
#calculate distance between two location
geodesic((34.16981,-118.37622),(34.11479-118.44739)).mi

8741.52204357605

In [0]:
df0.index[1]

156

In [0]:
df0.iloc[0].LON

-118.2573

In [0]:
#Data Preparing
df0 = df.sample(7) #randomly pick 7 rows
df0["demand"] = df0['sales']*100 #generate the demand
mini = int(min(df0['demand']))
maxi = int(max(df0['demand']))
df0['supply'] =  random.sample(range(mini,maxi),7)#generate the supply
df0.head()

Unnamed: 0       LAT        LON  sce  sales  demand  supply
119         119  34.22472 -118.53460    0   1.32   132.0     255
138         138  34.08144 -118.30447    0   2.27   227.0     251
141         141  34.04908 -118.29052    0   1.16   116.0     205
4             4  34.03975 -118.30395    0   2.57   257.0     220
318         318  33.93926 -118.23681    0   1.00   100.0     183

In [0]:
import numpy as np

g1 = lambda x: max(0, 2*x[0]-x[1]+3*x[2]-4)
g2 = lambda x: max(0, -x[0]-x[1]+2*x[2]+2)

I1 = lambda x : 1 if 2*x[0]-x[1]+3*x[2]-4>=0 else 0
I2 = lambda x : 1 if -x[0] - x[1] +2*x[2]+2>=0 else 0

gradientH = lambda x, rho: np.array([np.exp(x[0]-x[1]+2*x[0]), -x[0]+4*x[1]-x[2], -x[1]+2*x[2]-3])+\
                        rho * np.array([4.0, -2.0, 6.0])*I1(x)*(2*x[0]-x[1]+3*x[2]-4)+\
                        rho * np.array([-2.0, -2.0, 4.0])*I2(x)*(-x[0]-x[1]+2*x[2]+2)

def penaltyMethod(g1,g2, gradientH, rho=1, beta=2, c=0.1, e_0=0.01, e_v = 0.0001):
    x = np.array([.0,.0,.0])
    while g1(x)**2+g2(x)**2 >e_v:
        alpha = c/rho
        while True:
            h = gradientH(x, rho)
            x = x-alpha*h
            print('RHO: ', rho)
            print(x)
            print('g1(x): ',g1(x),'g2(x)', g2(x))
            if np.linalg.norm(h) < e_0:
                break
        rho = beta * rho
    return x

penaltyMethod(g1, g2, gradientH)

RHO:  1
[ 0.3  0.4 -0.5]
g1(x):  0 g2(x) 0.2999999999999998
RHO:  1
[ 0.19512787  0.28       -0.18      ]
g1(x):  0 g2(x) 1.164872127070013
RHO:  1
[ 0.29238775  0.40248721 -0.28194885]
g1(x):  0 g2(x) 0.7412273402613818
RHO:  1
[ 0.27988388  0.39078169 -0.1818013 ]
g1(x):  0 g2(x) 0.9657318427408996
RHO:  1
[ 0.31637616  0.43742364 -0.1926556 ]
g1(x):  0 g2(x) 0.8608889949919776
RHO:  1
[ 0.32174069  0.44700404 -0.15473772]
g1(x):  0 g2(x) 0.921779836592302
RHO:  1
[ 0.33819336  0.46925869 -0.14780171]
g1(x):  0 g2(x) 0.8969445450901268
RHO:  1
[ 0.34506599  0.47998329 -0.13009331]
g1(x):  0 g2(x) 0.914764093505755
RHO:  1
[ 0.35378731  0.49244006 -0.12198196]
g1(x):  0 g2(x) 0.9098087112266551
RHO:  1
[ 0.35911289  0.50060631 -0.11226505]
g1(x):  0 g2(x) 0.9157507080248157
RHO:  1
[ 0.36424185  0.50819871 -0.10605169]
g1(x):  0 g2(x) 0.9154560606802495
RHO:  1
[ 0.36791887  0.51382946 -0.1002039 ]
g1(x):  0 g2(x) 0.917843860695958
RHO:  1
[ 0.37110194  0.51863794 -0.09591772]
g1(x): 

g1(x):  0 g2(x) 0.035277259947996686
RHO:  32
[ 0.46174531  0.56657749 -0.46820018]
g1(x):  0 g2(x) 0.03527684461896774
RHO:  32
[ 0.46171488  0.56653046 -0.46823911]
g1(x):  0 g2(x) 0.035276432242759004
RHO:  32
[ 0.46168468  0.56648373 -0.46827778]
g1(x):  0 g2(x) 0.03527602279413644
RHO:  32
[ 0.46165471  0.56643729 -0.4683162 ]
g1(x):  0 g2(x) 0.0352756162481751
RHO:  32
[ 0.46162496  0.56639113 -0.46835435]
g1(x):  0 g2(x) 0.03527521258025201
RHO:  32
[ 0.46159544  0.56634525 -0.46839225]
g1(x):  0 g2(x) 0.035274811766041525
RHO:  32
[ 0.46156615  0.56629966 -0.46842989]
g1(x):  0 g2(x) 0.03527441378150975
RHO:  32
[ 0.46153707  0.56625434 -0.46846728]
g1(x):  0 g2(x) 0.03527401860290902
RHO:  32
[ 0.46150821  0.56620931 -0.46850443]
g1(x):  0 g2(x) 0.035273626206774544
RHO:  32
[ 0.46147957  0.56616456 -0.46854132]
g1(x):  0 g2(x) 0.03527323656991643
RHO:  32
[ 0.46145114  0.56612008 -0.46857797]
g1(x):  0 g2(x) 0.03527284966941968
RHO:  32
[ 0.46142292  0.56607588 -0.46861437]
g

g1(x):  0 g2(x) 0.007073954094188206
RHO:  128
[ 0.4620195   0.56438386 -0.48218675]
g1(x):  0 g2(x) 0.009223140562200527
RHO:  128
[ 0.46208733  0.56444903 -0.48233791]
g1(x):  0 g2(x) 0.008787811496831388
RHO:  128
[ 0.46206784  0.56442687 -0.48231466]
g1(x):  0 g2(x) 0.008875966067898311
RHO:  128
[ 0.46206605  0.56442241 -0.48232672]
g1(x):  0 g2(x) 0.008858091165328652
RHO:  128
[ 0.46206069  0.56441438 -0.48233162]
g1(x):  0 g2(x) 0.008861692143696587
RHO:  128
[ 0.46205606  0.56440709 -0.48233795]
g1(x):  0 g2(x) 0.008860943302685165
RHO:  128
[ 0.4620513   0.56439966 -0.48234398]
g1(x):  0 g2(x) 0.008861075534441154
RHO:  128
[ 0.46204657  0.56439227 -0.48235006]
g1(x):  0 g2(x) 0.00886102934264521
RHO:  128
[ 0.46204185  0.56438489 -0.48235612]
g1(x):  0 g2(x) 0.008861019323956443
RHO:  128
[ 0.46203713  0.56437752 -0.48236217]
g1(x):  0 g2(x) 0.008861002012612751
RHO:  128
[ 0.46203243  0.56437016 -0.48236821]
g1(x):  0 g2(x) 0.008860986212358757
RHO:  128
[ 0.46202773  0.564

array([ 0.46128731,  0.56317824, -0.48333801])

In [0]:
import numpy as np
from sklearn import linear_model
X = np.array([[-1, -1], [-2, -1], [1, 1], [2, 1]])
Y = np.array([1, 1, 2, 2])
clf = linear_model.SGDClassifier(max_iter=1000, tol=1e-3)
clf.fit(X, Y)
SGDClassifier()

NameError: name 'SGDClassifier' is not defined

In [0]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

# we create 20 points
np.random.seed(0)
X = np.r_[np.random.randn(10, 2) + [1, 1], np.random.randn(10, 2)]
y = [1] * 10 + [-1] * 10
sample_weight = 100 * np.abs(np.random.randn(20))
# and assign a bigger weight to the last 10 samples
sample_weight[:10] *= 10

# plot the weighted data points
xx, yy = np.meshgrid(np.linspace(-4, 5, 500), np.linspace(-4, 5, 500))

# fit the unweighted model
clf = linear_model.SGDClassifier(alpha=0.01, max_iter=100)
clf.fit(X, y)
Z = clf.decision_function(np.c_[xx.ravel(), yy.ravel()])
Z = Z.reshape(xx.shape)

# fit the weighted model
clf = linear_model.SGDClassifier(alpha=0.01, max_iter=100)
clf.fit(X, y, sample_weight=sample_weight)
Z = clf.decision_function(np.c_[xx.ravel(), yy.ravel()])
Z = Z.reshape(xx.shape)


In [0]:
clf


SGDClassifier(alpha=0.01, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=100, n_iter_no_change=5, n_jobs=None, penalty='l2',
              power_t=0.5, random_state=None, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)